{
 "title": "RabbitMQ Metrics from rabbitmq_exporter",
 "description": "Metrics from rabbitmq_exporter >= v1.0.0-RC6 \n",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(rabbitmq_running,node)"
   },
   {
    "name": "vhost",
    "label": "Vhost",
    "query": "label_values(rabbitmq_queue_messages,vhost)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(rabbitmq_queue_messages,queue)"
   }
  ]
 },
 "panels": [
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status  ($node)",
   "type": "singlestat",
   "description": "$node",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_running{node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Queued Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Messages in queue  ($queue)",
   "type": "gauge",
   "description": "Queue: $queue",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "repeat": "queue",
   "targets": [
    {
     "expr": "max_over_time(rabbitmq_queue_messages{vhost=~\"$vhost\",queue=~\"$queue\"}[1m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}:{{durable}}" }
   ]
  },
  {
   "title": "Messages/vhost  ($vhost)",
   "type": "graph",
   "description": "vhost: $vhost",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready)",
     "legendFormat": "{{vhost}}:ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total)",
     "legendFormat": "{{vhost}}:published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total)",
     "legendFormat": "{{vhost}}:delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged)",
     "legendFormat": "{{vhost}}:unack"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_consumersTotal", "legendFormat": "{{instance}}:consumers" }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queuesTotal", "legendFormat": "{{instance}}:queues" }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_channelsTotal", "legendFormat": "{{instance}}:channels" }
   ]
  },
  {
   "title": "FIle descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_fd_used{node=\"$node\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_fd_total{node=\"$node\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connectionsTotal", "legendFormat": "{{instance}}:connections" }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_exchangesTotal", "legendFormat": "{{instance}}:exchanges" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{node=\"$node\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{node=\"$node\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_sockets_used{node=\"$node\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_sockets_total{node=\"$node\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  }
 ]
}